// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upbnysrcdcpumjyjhysy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYm55c3JjZGNwdW1qeWpoeXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNzk2NTMsImV4cCI6MjA1Njk1NTY1M30.azZU9tUlojBLAUqxMs-54uUCdfsfksabJXMCO9j1QBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);